name: Make and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Safer than using ubuntu-latest for now

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache library directory
      uses: actions/cache@v3
      with:
        path: |
          ~/lib
        key: ${{ runner.os }}-lib

    - name: Build with Make
      run: make -j

    - name: Run Tests
      run: make test
